version: '3.8'

services:
  oracle:
    image: container-registry.oracle.com/database/enterprise:12.2.0.1-slim
    container_name: oracle
    environment:
      - ORACLE_PWD=SYSADMIN
      - ORACLE_CHARACTERSET=AL32UTF8
      - ORACLE_BASE=/opt/oracle
      - ORACLE_HOME=/opt/oracle/product/12.2.0.1/dbhome_1
      - ORACLE_SID=ORCLCDB
    volumes:
      - oracle_data:/opt/oracle/oradata
    ports:
      - "1521:1521"
      - "5500:5500"
    restart: always

volumes:
  oracle_data:
    driver: local